<?php
// Include the connection file
include 'db_connect.php';

// Function to display the privacy policy content
function display_privacy_policy()
{
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Privacy Policy - FoodHub</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            .container {
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #fff;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1, h2, h3 {
                color: #333;
            }
            p {
                color: #555;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Privacy Policy</h1>
            <p>Welcome to FoodHub, an application designed to provide users with a convenient food ordering and delivery experience. Our goal is to connect customers with restaurants and enhance dining convenience. This Privacy Policy explains how we collect, use, and protect your personal data when you use our service.</p>
            
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words with initial letters capitalized have meanings defined under the following conditions. These definitions will have the same meaning whether in singular or plural form.</p>
            
            <h3>Definitions</h3>
            <ul>
                <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
                <li><strong>Application:</strong> Refers to FoodHub, the software provided by the Company.</li>
                <li><strong>Company:</strong> Refers to FoodHub.</li>
                <li><strong>Country:</strong> Tamil Nadu, India.</li>
                <li><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, cellphone, or tablet.</li>
                <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> The FoodHub Application.</li>
                <li><strong>Service Provider:</strong> Any person or entity processing data on behalf of the Company.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
                <li><strong>You:</strong> The individual or entity accessing or using the Service.</li>
            </ul>
            
            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Delivery address and order details</li>
            </ul>
            
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device\'s IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data. When accessing the Service via a mobile device, additional information such as device type, unique ID, IP address, operating system, and browser type may also be collected.</p>
            
            <h4>Order Data</h4>
            <p>We may collect food order details such as restaurant name, items ordered, payment method, and delivery instructions. This data is used to process your order, improve recommendations, and enhance your overall food ordering experience.</p>
            
            <h2>Sharing Your Personal Data</h2>
            <ul>
                <li><strong>With Service Providers:</strong> To process payments, deliver orders, and analyze the use of our Service.</li>
                <li><strong>For Business Transfers:</strong> During mergers, sales, or acquisitions.</li>
                <li><strong>With Affiliates:</strong> Including our parent company and other subsidiaries under common control.</li>
                <li><strong>With Restaurant Partners:</strong> To fulfill your food orders and provide related services.</li>
                <li><strong>With Other Users:</strong> When leaving reviews or interacting in public sections of the app.</li>
                <li><strong>With Your Consent:</strong> For any other purpose with your explicit consent.</li>
            </ul>
            
            <h2>Retention of Your Personal Data</h2>
            <p>We will retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, and to comply with legal obligations. Order history may be retained to provide better recommendations and support customer queries.</p>
            
            <h2>Security of Your Personal Data</h2>
            <p>We strive to protect your data but cannot guarantee absolute security. We use commercially acceptable methods to safeguard your Personal Data.</p>
            
            <h2>Children\'s Privacy</h2>
            <p>Our Service does not target individuals under 13. We do not knowingly collect data from this age group. If you are a parent or guardian and become aware of such data collection, please contact us.</p>
            
            <h2>Changes to this Privacy Policy</h2>
            <p>We may update this Privacy Policy and will notify you of any changes by posting the new policy on this page. Please review the policy periodically for updates.</p>
            
            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:foodhub.support@example.com">app.simats@saveetha.com</a>.</p>
            
            <p>© 2025 FoodHub. All rights reserved.</p>
        </div>
    </body>
    </html>';
}

display_privacy_policy();
?>
